### ISSUE TITLE
Mail not going.

### ISSUE THREAD

**Issue by saintofinternet** [mashsajid/mail0#1]
i tried using your script and it works fine... but there is no email in my inbox to which i am trying to send an mail. 

i am using smtp2go servers and also checked the video link at https://www.youtube.com/watch?v=doJWJD6qxG0

can you please help where i might be going wrong?

**Comment by mashsajid** [comment]
@saintofinternet New update is coming...It might fix your problem.

**Comment by mashsajid** [comment]
And can you tell me which you are using?

**Comment by mashsajid** [comment]
If the latest update work for you then close the issue.Have a good day!

**Comment by mashsajid** [comment]
Problem fixed in v1.2. Thanks for submitting this issue.
