### ISSUE TITLE
rejected by the mail server, error follows

### ISSUE THREAD

**Issue by progsss** [mashsajid/mail0#2]
Jan 23 14:21:06 ubuntu sendemail[4801]: WARNING => The recipient <myemail@domain.com> was rejected by the mail server, error follows:
Jan 23 14:21:06 ubuntu sendemail[4801]: WARNING => Received: 	550 that smtp username's account is not allowed to send
Jan 23 14:21:06 ubuntu sendemail[4801]: ERROR => Exiting. No recipients were accepted for delivery by the mail server.

mb smtp2go not relevant?

**Comment by mashsajid** [comment]
Create another account on smtp2go...
