### ISSUE TITLE
SMTP user not allowed

### ISSUE THREAD

**Issue by jimbillini** [mashsajid/mail0#3]
Jan 31 06:07:25 bt sendEmail[7028]: WARNING => The recipient <jimbillini@gmail.com> was rejected by the mail server, error follows:
Jan 31 06:07:25 bt sendEmail[7028]: WARNING => Received:        550 that smtp username's account is not allowed to send
Jan 31 06:07:25 bt sendEmail[7028]: ERROR => Exiting. No recipients were accepted for delivery by the mail server.

**Comment by mashsajid** [comment]
Create another account on smtp2go...
